package com.accounting.util;

import com.accounting.database.DBConnection;
import org.slf4j.Logger;

import java.io.*;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

public class BackupService {

    private static final Logger log = AppLogger.get(BackupService.class);
    private static final DateTimeFormatter TIMESTAMP_FMT = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");

    /**
     * Takes a SQL dump backup of the current database to the specified directory.
     * Returns the path of the created backup file.
     */
    public static String backupDatabase(String backupDir) throws Exception {
        File dir = new File(backupDir);
        if (!dir.exists() && !dir.mkdirs()) {
            throw new IOException("Could not create backup directory: " + backupDir);
        }

        String timestamp = LocalDateTime.now().format(TIMESTAMP_FMT);
        String dbName = DBConnection.getDatabaseName();
        String fileName = dbName + "_backup_" + timestamp + ".sql";
        File backupFile = new File(dir, fileName);

        log.info("Starting database backup to: {}", backupFile.getAbsolutePath());

        try (Connection conn = DBConnection.getConnection();
             PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(backupFile)))) {

            DatabaseMetaData meta = conn.getMetaData();
            writer.println("-- Database Backup: " + dbName);
            writer.println("-- Date: " + LocalDateTime.now());
            writer.println("-- Generated by Account Management System");
            writer.println();
            writer.println("SET FOREIGN_KEY_CHECKS=0;");
            writer.println();

            // Get all tables
            List<String> tables = new ArrayList<>();
            try (ResultSet rs = meta.getTables(dbName, null, "%", new String[]{"TABLE"})) {
                while (rs.next()) {
                    tables.add(rs.getString("TABLE_NAME"));
                }
            }

            for (String table : tables) {
                log.info("Backing up table: {}", table);

                // Get CREATE TABLE statement
                try (Statement stmt = conn.createStatement();
                     ResultSet rs = stmt.executeQuery("SHOW CREATE TABLE `" + table + "`")) {
                    if (rs.next()) {
                        writer.println("-- Table: " + table);
                        writer.println("DROP TABLE IF EXISTS `" + table + "`;");
                        writer.println(rs.getString(2) + ";");
                        writer.println();
                    }
                }

                // Get table data
                try (Statement stmt = conn.createStatement();
                     ResultSet rs = stmt.executeQuery("SELECT * FROM `" + table + "`")) {

                    ResultSetMetaData rsMeta = rs.getMetaData();
                    int colCount = rsMeta.getColumnCount();

                    while (rs.next()) {
                        StringBuilder sb = new StringBuilder();
                        sb.append("INSERT INTO `").append(table).append("` VALUES (");

                        for (int i = 1; i <= colCount; i++) {
                            if (i > 1) sb.append(", ");
                            Object val = rs.getObject(i);
                            if (val == null) {
                                sb.append("NULL");
                            } else if (val instanceof Number) {
                                sb.append(val);
                            } else {
                                sb.append("'").append(escapeSQL(val.toString())).append("'");
                            }
                        }
                        sb.append(");");
                        writer.println(sb);
                    }
                    writer.println();
                }
            }

            writer.println("SET FOREIGN_KEY_CHECKS=1;");
            writer.println();
            writer.println("-- Backup complete");
        }

        log.info("Database backup completed: {}", backupFile.getAbsolutePath());
        return backupFile.getAbsolutePath();
    }

    /**
     * Restores the database from a SQL dump file.
     */
    public static void restoreDatabase(String backupFilePath) throws Exception {
        File backupFile = new File(backupFilePath);
        if (!backupFile.exists()) {
            throw new FileNotFoundException("Backup file not found: " + backupFilePath);
        }

        log.info("Starting database restore from: {}", backupFilePath);

        try (Connection conn = DBConnection.getConnection();
             BufferedReader reader = new BufferedReader(new FileReader(backupFile))) {

            conn.setAutoCommit(false);
            Statement stmt = conn.createStatement();

            StringBuilder currentStatement = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                line = line.trim();

                // Skip comments and empty lines
                if (line.isEmpty() || line.startsWith("--")) {
                    continue;
                }

                currentStatement.append(line).append(" ");

                // Execute when we find a semicolon
                if (line.endsWith(";")) {
                    String sql = currentStatement.toString().trim();
                    if (!sql.isEmpty()) {
                        try {
                            stmt.execute(sql);
                        } catch (SQLException e) {
                            log.warn("Skipping failed statement: {} - Error: {}", 
                                sql.substring(0, Math.min(100, sql.length())), e.getMessage());
                        }
                    }
                    currentStatement.setLength(0);
                }
            }

            conn.commit();
            conn.setAutoCommit(true);
            stmt.close();
        }

        log.info("Database restore completed from: {}", backupFilePath);
    }

    /**
     * Lists all backup files in the specified directory.
     */
    public static List<File> listBackups(String backupDir) {
        List<File> backups = new ArrayList<>();
        File dir = new File(backupDir);
        if (dir.exists() && dir.isDirectory()) {
            File[] files = dir.listFiles((d, name) -> name.endsWith(".sql") && name.contains("_backup_"));
            if (files != null) {
                // Sort newest first
                java.util.Arrays.sort(files, (a, b) -> Long.compare(b.lastModified(), a.lastModified()));
                for (File f : files) {
                    backups.add(f);
                }
            }
        }
        return backups;
    }

    /**
     * Cleans up old backups, keeping only the specified number of most recent ones.
     */
    public static void cleanupOldBackups(String backupDir, int keepCount) {
        List<File> backups = listBackups(backupDir);
        if (backups.size() > keepCount) {
            for (int i = keepCount; i < backups.size(); i++) {
                File old = backups.get(i);
                if (old.delete()) {
                    log.info("Deleted old backup: {}", old.getName());
                }
            }
        }
    }

    private static String escapeSQL(String value) {
        if (value == null) return "";
        return value
                .replace("\\", "\\\\")
                .replace("'", "\\'")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t")
                .replace("\0", "");
    }
}
